### ISSUE TITLE
Can't find pv_train.csv

### ISSUE THREAD

**Issue by sanjaybhasin** [sandialabs/lapart-python#1]
When trying to run pv.rst, unable to locate file pv_train.csv.
df = pd.read_csv('pv_train.csv')

Please help.

**Comment by sanjaybhasin** [comment]
I tried to use my own data but the methods train and test can't find the missing files... Please help.
FileNotFoundError: [Errno 2] File templates/maxminA.csv does not exist: 'templates/maxminA.csv'

**Comment by cbirkj** [comment]
Hi Sanjay,
Sorry I missed this email.  Are you still working on this?

I will have time to look into it next week.

Birk

**Comment by sanjaybhasin** [comment]
Hi Birk,

Yes I am still working on this.
Will appreciate it if you could please fix this aspect.

Best regards,
Sanjay

**Comment by cbirkj** [comment]
Hi Sanjay
Yes I will.  I won’t be around my computer this weekend but will work on it
during the middle of next week.

Birk

**Comment by cbirkj** [comment]
Hi Sanjay, 

To address the maxminA.csv question:
It may not be the best set up.  But, for the current script to work the user has to set up a templates folder with the maximinA.csv and maxminB.csv.  The files define the max and min values for the A and B side inputs.  Use the xor example as a reference.  

The code will create the TA, TB, and L matrix and write those into the templates folder.

pv_train.csv data comment:
The repo does not include the photovoltaic (PV) system example.  Are you looking for PV data?

I hope that helps.
Birk

**Comment by johnblackhill** [comment]
Hi Birk,

Would it be possible to include in the repository the file "pv_train.csv" to be able to reproduce the LAPART algorithm? I think it could be of great help to understand how the algorithm works in different applications, specially on the Solar PV Example.

If this is not possible, directions on how to get a similar dataset to make that example work would be greatly appreciated!

Kind regards,
John.

**Comment by johnblackhill** [comment]
Hello Birk, any news on the "pv_train.csv" data? I still think it can be of great help to see how the data must be feeded to the LAPART algorithm in order to make it work :D 

Kind regards,
John.

**Comment by cbirkj** [comment]
Hi John,
I just added some PV data to the repo.  I did it in a hurry and added one file named solarPVdata.csv into the examples/SolarPV folder.  The file contains about 7 days of data - I can add more data if needed.

Thanks
Birk

**Comment by johnblackhill** [comment]
Hi Birk,

Thanks for posting PV Data! I have been modifying the original code to make it work with the current file (solarPVdata.csv) by changing all references to the new headers:

- _Sys1Wdc_Avg_ to _Wac_
- _POAIrrad1_Avg_ to _POAIrrad_

I have also created the 'templates' folder with empty files for maxMinA.csv and maxMinB.csv but Pandas raises a **"pandas.errors.EmptyDataError: No columns to parse from file"** error, which I assume is because these files must be filled beforehand. I have been examining the XOR example (as you suggested to Sanjay) and I have a few deductions I would like to be confirmed by you, if possible:

**- maxMinA.csv:** It has two rows defining the maximum and minimum values for _Wac_ and _POAIrrad_, in that order.

**- maxMinB.csv:** It just has one row, which I assume is to define the maximum and minimum values of the class you want to predict, which in this case is POAIrrad.

Are these deductions correct?

Thanks in advance! :)

**Comment by johnblackhill** [comment]
Hello Birk,

Thanks for posting PV Data! I have been modifying the original PV code example to make it work with the current file (solarPVdata.csv) by changing all references to the new headers:

    Sys1Wdc_Avg to Wac
    POAIrrad1_Avg to POAIrrad

I have also created both maxminA.csv and maxminB.csv with the adequate headers and values you kindly uploaded inside "solarPVdata.csv":

     One row inside maxminA contains the max and min values for POAIrrad.
     The row inside maxminB contains the max and min values for Wac.

Training and testing procedures go as planned, so I think this issue can be marked as solved and closed!

Thanks again for this implementation of the LAPART algorithm! It works like a charm :D 

P.S: In the near future, once I clean up my code a little bit, I might be submitting a Pull Request with a basic terminal interface and a more verbose output so you can observe what happens inside the training procedure :)

**Comment by LittleSpeedy** [comment]
Hi John and Birk, 

I have been following on with the work you have done on the repo here and have been trying to get the available PV dataset (solarPVdata.csv) working. I have created maximA and maximB as i got that same error, mine look like:

MaximA: 
  | max | min
0 | 3102.629 | -4.11217
1 | 1274.304 | 0

MaximB:
  | max | min
0 | 3102.629 | -4.11217

I have resolved the initial error 'FileNotFoundError: [Errno 2] File templates/maxminA.csv does not exist: 'templates/maxminA.csv' by adding these to the local templates folder. 

I am now receiving this error, however:

runfile('C:/Users/jackw/.spyder-py3/Lampart PV Forecasting.py', wdir='C:/Users/jackw/.spyder-py3')
Traceback (most recent call last):

  File "C:\Users\jackw\.spyder-py3\Lampart PV Forecasting.py", line 32, in <module>
    C,T,Tn,df,time_test = test.lapArt_test(xAtest,rhoA=rA,rhoB=rB,memory_folder=r'C:\Users\jackw\Downloads\templates')

  File "C:\Users\jackw\anaconda3\lib\site-packages\lapart\test.py", line 153, in lapArt_test
    ann = test(xA,TA,TB,L,rhoA,rhoB,beta,alpha,nep,memory_folder)

  File "C:\Users\jackw\anaconda3\lib\site-packages\lapart\test.py", line 50, in __init__
    mmA = np.hstack([past_maxA,current_maxA,past_minA,current_minA]).T

  File "<__array_function__ internals>", line 5, in hstack

  File "C:\Users\jackw\anaconda3\lib\site-packages\numpy\core\shape_base.py", line 346, in hstack
    else:

  File "<__array_function__ internals>", line 5, in concatenate

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

Could anyone assist me in troubleshooting this error? Its taken a lot of time already but I am quite new to Python and to this algorithm, in particular. 

Thank you again for your help!
